name: Bug
description: Ticket for investigating a bug.
projects: ["tunedd/Tunedd"]
labels: ["bug"]
type: "Bug"
body:
  - type: dropdown
    id: severity
    validations:
      required: true
    attributes:
      label: "Severity"
      description: "Measure of much the bug impacts the functionality of the app"
      options:
        - "Low"
        - "Medium"
        - "High"
        - "Critical"

  - type: checkboxes
    id: environment
    validations:
      required: true
    attributes:
      label: "Environment"
      description: "The environment(s) where the bug occurs"
      options:
        - label: "Development"
        - label: "Staging"
        - label: "Production"
        - label: "Infrastructure"

  - type: textarea
    id: description-current-behaviour
    validations:
      required: true
    attributes:
      label: "Current behaviour"
      description: "The current, incorrect behaviour"

  - type: textarea
    id: description-expected-behaviour
    validations:
      required: true
    attributes:
      label: "Expected behaviour"
      description: "The expected behaviour in a working environment"

  - type: textarea
    id: reproduction-steps
    validations:
      required: true
    attributes:
      label: "Steps to reproduce"
      description: "Step-by-step approach to reproducing the bug"
