name: Spike
description: Ticket for a new feature.
projects: ["tunedd/Tunedd"]
type: "Spike"
body:
  - type: input
    id: focus
    validations:
      required: true
    attributes:
      label: Focus
      description: Provide the main focus or objective of the spike.

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "Description"
      description: "Provide a detailed description of the spike."

  - type: textarea
    id: research_findings
    validations:
      required: false
    attributes:
      label: "Research findings"

  - type: textarea
    id: recommendation
    validations:
      required: false
    attributes:
      label: "Recommendation"

  - type: textarea
    id: next_steps
    validations:
      required: false
    attributes:
      label: "Next steps"
