name: Spike
description: Ticket for a spike.
projects: ["tunedd/Tunedd"]
type: "Spike"
body:
  - type: input
    id: focus
    validations:
      required: true
    attributes:
      label: Focus
      description: "The main focus or objective of the spike"

  - type: input
    id: timebox
    validations:
      required: true
    attributes:
      label: Recommended timebox
      description: "Suggested duration for the spike"

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "Description"
      description: "Detailed description of the spike"
      placeholder: "Why do we need to investigate this?\nWhat decision depends on the spike?"

  - type: textarea
    id: research_findings
    validations:
      required: false
    attributes:
      label: "Research findings"
      description: "Summary of the research findings relevant to the spike"

  - type: textarea
    id: recommendation
    validations:
      required: false
    attributes:
      label: "Recommendations"
      description: "Proposed next steps or solutions based on the findings"

  - type: textarea
    id: next_steps
    validations:
      required: false
    attributes:
      label: "Next steps"
      description: "Subsequent actions based on the recommendations, if applicable"
