name: Ticket (Classic)
description: Create a work order for tracking issues or tasks.
projects: ["tunedd/Tunedd"]
body:
  - type: input
    id: summary
    validations:
      required: true
    attributes:
      label: Summary
      description: Provide a brief summary of the task.
      placeholder: "Brief overview of the task"

  - type: textarea
    id: description
    validations:
      required: false
    attributes:
      label: Description
      description: Provide a detailed description of the task.
      placeholder: "Detailed explanation of the task"

  - type: textarea
    id: acceptance_criteria
    validations:
      required: true
    attributes:
      label: Acceptance criteria
      description: Define the conditions that must be met for this ticket to be considered complete.
      placeholder: "What - Clearly state the feature or functionality.\nConditions - Specify the exact inputs, outputs, or behaviours.\nTestability - Ensure it can be objectively validated.\nFormat - Consider using structured formats like \"Given, When, Then\" for clarity."

  - type: textarea
    id: notes
    validations:
      required: false
    attributes:
      label: Additional notes
      description: Include any additional information or context relevant to this ticket.
      placeholder: "Any other relevant details"
